const Constants = {
  LOGIN_TEXT: "Login/Signup",
  FIND_BUYERS_TEXT: "Find Buyers",
  FIND_SELLERS_TEXT: "Find Sellers",
  CATEGORY_TEXT: "Categories",
  EXPORTERS_TEXT: "List of Buyers in India ",
  VIEW_MORE_TEXT: "View more",
  TAB1_TEXT: "Home",
  TAB2_TEXT: "About",
  TAB3_TEXT: "FPOs",
  TAB4_TEXT: "Agents",
  TAB5_TEXT: "Products",
  TAB6_TEXT: "Contact",
  TAB7_TEXT: "Subcriptions",
  TAB8_TEXT: "Complaints",
  PRICING_TEXT: "Pricing and  Plans",
  STARTER_PLAN_TEXT: "Starter Plan",
  MONTH_TEXT: "Month",
  PRICING_DESCRIPTION:
    "Ideal for existing stores ready to get started with Toast.",
  BUY_TEXT: "Buy",
  LEARN_MORE_TEXT: "Learn more",
  SELLER_DETAILS_TEXT: "View Seller details",
  CREATE_DEAL_TEXT: "Create a Deal",
  PRODUCT_DESC_TEXT: "Description",
  PRODUCT_TITLE1_TEXT: "BOTANICAL NAME",
  PRODUCT_TITLE2_TEXT: "FAMILY",
  PRODUCT_TITLE3_TEXT: "ORIGIN",
  PRODUCT_TITLE4_TEXT: "MAJOR COMMERCIAL VARIETIES",
  PRODUCT_TITLE5_TEXT: "MAJOR PRODUCING STATES/DISTRICTS IN INDIA",
  PRODUCT_TITLE6_TEXT: "TOTAL AREA IN INDIA",
  PRODUCT_TITLE7_TEXT: "TOTAL PRODUCTION IN INDIA",
  PRODUCT_TITLE8_TEXT: "STORAGE CONDITIONS",
  PRODUCT_TITLE9_TEXT: "HARVESTING",
  SEND_ENQUIRY_TEXT: "Send Enquiry",
  SEND_TEXT: "Send",
  CALL_ME_BACK_TEXT: "call me back",
  LIKE_TEXT: "Like",
  BACK_TO_TOP_TEXT: "Back to top",
  CONTACT_INFO_TEXT: "Contact Info",
  CONTACT_US_TEXT: "Contact Us",
  REGISTERED_OFFICE_TEXT: "Registered Office Address",
  SOCIAL_MEDIA_TEXT: "Social Media",
  SEND_MESSAGE_TEXT: "Send message",
  COMPLAINT_HEADER_TEXT: "Complaint Form",
  REQUEST_CALL_TEXT: "Request Call",
  ACTIVE_COMPLAINTS_TEXT: "Active Compaints",
  DONE_TEXT: "Done",
  REVIEW_TEXT: "Review",
  ACCEPT_TEXT: "Accept",
  CONTINUE_TEXT: "Continue",
  SUBMIT_TEXT: "Submit",
  USERNAME_TEXT: "User name",
  PASSWORD_TEXT: "Password",
  FORGOT_PASSWORD_TEXT: "Forgot password ?",
  REGISTER_TEXT: "Register Now",
  ENTER_TEXT: "Enter",
  BACKSPACE_TEXT: "Backspace",
  ARROWLEFT_TEXT: "ArrowLeft",
  OTP_VALUE: "123456",
  TEST_USERNAME: "test",
  TEST_PASSWORD: "test",
};

export default Constants;
